### ISSUE TITLE
Clarify LICENSE

### ISSUE THREAD

**Issue by ewindisch** [nickmerwin/node-coveralls#121]
There is no LICENSE file in this repository, nor does the README indicate any license. Lacking clarity, this is likely a blocker for adoption by many users.  The npm repository signifies that it is BSD-2-Clause licensed, although again, this seems not to be indicated anywhere except npm.

Thanks!

**Comment by tparnell8** [comment]
Why does a license file need to be present when the license is in the package.json file. I just ask because I don't know that much about licensing, but I would guess it being listed in the package.json file would be enough.

**Comment by jaredsmith** [comment]
It's because most of the open source licenses state that the text of the license must accompany the source code.  In the case of the BSD 2-clause license (which this package seems to be licensed under), the first clause is:

`Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.`

So, in short,  something can't really be BSD licensed without including the text of the BSD license.  (The same goes for the MIT license, etc.)

**Comment by honzajavorek** [comment]
Also currently it's not clear who is the copyright owner.
