### ISSUE TITLE
Pinned dependency, request@2.69.0 is broken

### ISSUE THREAD

**Issue by pwfisher** [nickmerwin/node-coveralls#133]
https://github.com/request/request/issues/2040

**Comment by seangenabe** [comment]
request@2.69.0 -> tough-cookie@2.2.2 is not secure. https://nodesecurity.io/advisories/130

**Comment by SimenB** [comment]
It's on 2.75 now.

The current one has a deprecation warning from request though, would be nice with another bump

**Comment by busches** [comment]
New warning is `request > node-uuid@1.4.7: use uuid module instead`. This is fixed in request `v2.79.0`, but request `v2.77.0` dropped support for all versions of node `<4` which would be a breaking change for this project. The same [PR](https://github.com/request/request/pull/2442) that was filed against request could and probably should be filed against here.

**Comment by pmuens** [comment]
Facing the same issue. 👍 for the version bump so that the new request package with `uuid` support is used.
