### ISSUE TITLE
Couldn't find a repository matching this job.

### ISSUE THREAD

**Issue by jcubic** [nickmerwin/node-coveralls#166]
I'm running coveralls from travis but (repo [jquery.terminal](https://github.com/jcubic/jquery.terminal/tree/devel)) it didn't get updated (last update was from two days ago) even that I commit changes, I've try to run from local system (GNU/Linux) and I've got this output:

```
[warn] "2017-05-09T18:40:08.553Z"  'Repo token could not be determined.  Continuing without it.This is necessary for pri
vate repos only, so may not be an issue at all.'                                                                       

/home/kuba/projects/jcubic/terminal/repo/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

I'm running this command:

```
ISTANBUL=./node_modules/istanbul/lib/cli.js

coveralls:
	$(ISTANBUL) cover node_modules/jasmine/bin/jasmine.js --captureExceptions && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js -v
```

(travis was running wihtout -v)

versions:
```javascript
  "devDependencies": {
    "coveralls": "^2.11.15",
    "istanbul": "^0.4.3",
    "jasmine": "^2.4.1",
    "jasmine-node": "^1.14.5",
  }
```
Is this because I'm running this locally? or is there something wrong with the repo?

**Comment by jcubic** [comment]
I don't get this message when running on travis with -v option (only about the token).

**Comment by skmexyz** [comment]
I've had this issue too.
On further investigation, turns out this issue is related to job id. Commenting `service_job_id` (in [`lib/getOptions.js`](https://github.com/nickmerwin/node-coveralls/blob/master/lib/getOptions.js#L22)) out appears to have fixed the issue.

I don't think this is an issue with the package, but more so with coveralls.

A fix to this solution would be to allow the `.coveralls.yml` file to take precedence over env variables (instead of what it's doing currently - directly accessing env variables even when the file is present).

Would this be something that can be considered? (if so, I can submit a pull request).

**Comment by rjdangcc** [comment]
I met the same case ,and it seems like 

> istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

cannot run in local system , just for travis to execute npm test

`Note: Travis runs npm test, so whatever target you create in your Makefile must be the target that npm test runs (This is set in package.json's 'scripts' property).`

https://github.com/nickmerwin/node-coveralls

**Comment by dinodsaurus** [comment]
Removing `ENV` variables and moving to `coveralls.yml` did the job for me

**Comment by SheikhG1900** [comment]
silly mistake from my side.
I was running `Travis` test but didn't configure `Coveralls`.

**Comment by paras20xx** [comment]
In my case, it happened when I made the commit directly from GitHub website.

In node_modules/coveralls/lib/fetchGitData.js (https://github.com/nickmerwin/node-coveralls/blob/master/lib/fetchGitData.js#L62) there is a regular expression
`var REGEX_COMMIT_DETAILS = /\nauthor (.+?) <(.+?)>.+\ncommitter (.+?) <(.+?)>.+\n?.+?\n\n(.*)/m;`

which then tries to match with the output from `git cat-file -p <commit/head-id>` (https://github.com/nickmerwin/node-coveralls/blob/master/lib/fetchGitData.js#L65)

When I commit from my local system:
```
$ git cat-file -p <commit-hash>
```
```
tree aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
parent bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
author Name Surname <mailid@email.com> 1234567890 +0000
committer Name Surname <mailid@email.com> 1234567890 +0000

My commit subject

```

When I commit from GitHub website:
```
$ git cat-file -p <commit-hash>
```
```
tree aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
parent bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
author Name Surname <mailid@users.noreply.github.com> 1234567890 +0000
committer Name Surname <mailid@email.com> 1234567890 +0000
gpgsig -----BEGIN PGP SIGNATURE-----

 abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz12
 34567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrst
 uvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijkl
 mnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcd
 efghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz123456
 7890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwx
 yz123
 -----END PGP SIGNATURE-----

My commit subject
```

Due to this different output, the above mentioned regex fails.
**Till when that regex issue gets fixed, the workaround would be to push commits from local system.**

Hope that helps someone :-)

**Comment by prologic** [comment]
Watch out for CI run in Docker containers (`docker build`) and your `.dockerignore` file. Make sure your `.coveralls.yml` is **really** being copied to your build environment/container "somehow".

**Comment by jcubic** [comment]
Wow, I've just read [the docs](https://github.com/nickmerwin/node-coveralls#running-locally) LOL, no one mention this in comment you need to get TOKEN from repo on coveralls.io and use

```
COVERALLS_REPO_TOKEN=<TOKEN> make coveralls
```

where my makefile have:
```
coveralls:
	$(CAT) ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
```

Didn't tested `.coveralls.yml` file though.

**Comment by rojosnow** [comment]
When I pass `COVERALLS_REPO_TOKEN` as an environmental variable, it ignores the `.coveralls.yml` file. If you're using Travis Pro and private repos, you need the `service_name: travis-pro` line in `.coveralls.yml`. Otherwise, the `service-name` will be `travis-ci` when providing `COVERALLS_REPO_TOKEN` as an environmental variable.

**Comment by kanekotic** [comment]
+1 to all the issues in the last few hours all my repositories that use coveralls are broken

**Comment by kanekotic** [comment]
I have found a workaround for now. I added to the script the token in the expected enviroment variable
```jspn
{
"scripts": {
"test:cov": "jest --coverage && cat ./coverage/lcov.info | COVERALLS_REPO_TOKEN='yourTokenHere' ./node_modules/coveralls/bin/coveralls.js"
}
}
```

**Comment by ericmorand** [comment]
@kanekotic Same here. What's happening?

**Comment by kanekotic** [comment]
@ericmorand not sure. There is an ongoing discussion in coveralls repo. It seems it started a few days ago randomly. But now it fails 100% of the time for most people.

**Comment by mortimr** [comment]
My builds started failing. I'm using travis-ci.

By adding both env variables `COVERALLS_REPO_TOKEN` with your repo token and `COVERALLS_SERVICE_NAME` to a different name than `travis-pro` (used the name of my repo), I made the build work again.

**Comment by nickmerwin** [comment]
Hi all, it turned out we had our webserver IPs accidentally blacklisted by Travis, so we couldn't query their API to get job info as coverage data was posted.

Apologies for the gap in service here! We're adding failsafes to warn us early about this in the future.
