### ISSUE TITLE
missing release notes and tag for v3.0.0

### ISSUE THREAD

**Issue by thecotne** [nickmerwin/node-coveralls#174]

**Comment by AlexSwensen** [comment]
As seen here: https://github.com/nickmerwin/node-coveralls/commit/5ebe57ffd8e761588f6be5bf53ec3c034b11e8ee

![screen shot 2017-10-03 at 10 35 05 am](https://user-images.githubusercontent.com/7460917/31133987-8e54d472-a826-11e7-96de-3f3b48b764af.png)

**Comment by Demven** [comment]
I was very confused by the absence of GitHub tag/release for v3.0.0. I need the changelog!

**Comment by ntwb** [comment]
I dug through the commit history to find the version I'm upgrading from `2.13.1`

Grabbing that commit hash b9032a18bd8d7fba7eaa0924a77e810ec4d0935a along with the `3.0.0` commit 2ed4d0958b524f7340ccdb9e87c023b30117f714 lets me compare changes since the first commit to the 3.0.0 commit: https://github.com/nickmerwin/node-coveralls/compare/b9032a18bd8d7fba7eaa0924a77e810ec4d0935a...2ed4d0958b524f7340ccdb9e87c023b30117f714

I hope that helps others here, but yes, tagging at a minimum on GitHub would be appreciated, a changelog would be ice cream 🍨 http://keepachangelog.com/

**Comment by dijonkitchen** [comment]
This might be helpful too for changelog generation: https://github.com/conventional-changelog/conventional-changelog

**Comment by gertsonderby** [comment]
v3.0.2, same problem.

Maybe automate this some, as has been suggested?

**Comment by nickmerwin** [comment]
Thanks @gertsonderby and @thecotne, I've added release notes for `v3.0.2`.
