### ISSUE TITLE
Error: The commit wasn't found on the repo

### ISSUE THREAD

**Issue by derekherman** [nickmerwin/node-coveralls#273]
I have a Coveralls setup that works perfectly in our public repos, but I used the same setup in a private repo, obviously adding the Coveralls token to Travis, and now I get this weird error about the commit not being found. Any ideas on what to do here? The PHPUnit coverage is reporting correctly to Coveralls but the JS coverage is failing. I've commented it out temporarily until I can find a solution, but that's not ideal.

```bash
> wp-scripts test-unit-js --coverage --coverageReporters=text-lcov | coveralls
TravisFoldPassesReporter
...1 passing test.
/home/travis/build/xwp/material-theme-builder-wp/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Bad response: 422 {"message":"Travis API Error: #\u003cCoveralls::Mash message=\"The job(285764075) couldn't be found\"\u003e. The commit  wasn't found on the repo xwp/material-theme-builder-wp","error":true}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-theme-builder-wp@ test:js:coveralls: `wp-scripts test-unit-js --coverage --coverageReporters=text-lcov | coveralls`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the material-theme-builder-wp@ test:js:coveralls script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-02-11T07_08_20_775Z-debug.log
```

**Comment by benpetty** [comment]
@derekherman I'm having the same issue using Travis-Pro. It's getting a commit hash that doesn't even exist in our repository. Where `$TRAVIS_COMMIT` is `50e440c5e3ec182607cb71370173cd884f33bc2a` the response from coveralls is:

```
Bad response: 422 {"message":"The commit 0023214bdfc259bef2a8e00444f77fa60825a5ba wasn't found on the repo OrgName/RepoNameThe commit 0023214bdfc259bef2a8e00444f77fa60825a5ba wasn't found on the repo OrgName/RepoName","error":true}
```

As you can see the commit hash is wrong, is not even in our repo:

```bash
$ git show 0023214bdfc259bef2a8e00444f77fa60825a5ba
fatal: bad object 0023214bdfc259bef2a8e00444f77fa60825a5ba
```

The above config includes `$COVERALLS_REPO_TOKEN` environment variable being sent to travis. If I remove `$COVERALLS_REPO_TOKEN`, I get this:

```
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

Even though the docs say this will work out of the box without it. I suppose it hasn't been tested for Travis-PRO or maybe something in Travis PRO has changed since the code was written.

I've submitted a PR that would definitely fix this. Instead of passing "HEAD", pass the actual `$TRAVIS_COMMIT` env var which will always exist in every travis build (pro/free).

Pull request here: #272 

Someone please merge this and release!
